### ISSUE TITLE
Select one result by default

### ISSUE THREAD

**Issue by tonatiuh** [siadat/chrome-ff#3]
I don't like to have to manually select the first match. I'd be nice if the first match were automatically selected.

**Comment by siadat** [comment]
Type your query and just press enter without selecting the first match, and it will act as if you selected the first match! In other words, selecting "Run FF command: query" will select the first actual match.

I wish the chromium extension API would have allowed us to remove the line before the first match, i.e., the extra useless line that says "Run FF command: query". Feel free to open an issue in https://bugs.chromium.org/p/chromium/issues/list, they might accept it if they are convinced there is demand.

**Comment by tonatiuh** [comment]
Hey, that's right. Thanks for the quick response. 
I'll check the chromium issues website.
